@{
    RootModule        = 'MyDevAliases.psm1'
    ModuleVersion     = '0.0.1'
    FunctionsToExport = @(
        # Git
        'Add-GitStage'
        'Add-GitStagePatch'
        'Reset-GitStage'
        'Move-Git'
        'Remove-Git'
        'Submit-GitCommit'
        'Submit-GitCommitAll'
        'Submit-GitCommitAmend'
        'Submit-GitCommitAmendNoEdit'
        'Reset-GitCommitMixed'
        'Reset-GitCommitSoft'
        'Reset-GitCommitHard'
        'Restore-Git'
        'Get-GitBranch'
        'Switch-GitBranch'
        'New-GitBranch'
        'Remove-GitBranch'
        'Merge-Git'
        'Stop-GitMerge'
        'Invoke-GitRebase'
        'Get-GitStash'
        'Save-GitStash'
        'Save-GitStashUntracked'
        'Receive-GitStash'
        'Remove-GitStash'
        'Clear-GitUntracked'
        'Clear-GitUntrackedX'
        'Get-GitStatus'
        'Get-GitDiff'
        'Get-GitStageDiff'
        'Get-GitLog'
        'Get-GitLog3'
        'Find-GitLog'
        'Show-Git'
        'Invoke-GitFetch'
        'Update-GitRemote'
        'Push-Git'
        # MyDevTools
        'Clear-Directory'
        'Remove-GitRepository'
        'Remove-NodeModule'
        # pnpm
        'New-PnpmViteProject'
        'New-PnpmNextJsProject'
        # PowerShell
        'Stop-PowerShellSession'
    )
    AliasesToExport   = @(
        # Git
        'a'
        'ap'
        'unst'
        'gmv'
        'grm'
        'c'
        'ca'
        'cam'
        'camn'
        'rem'
        'res'
        'reh'
        'restore'
        'che'
        'cheb'
        'bra'
        'brad'
        'merge'
        'mergea'
        'rebase'
        'stashl'
        'stash'
        'stashu'
        'pop'
        'drop'
        'cl'
        'clx'
        'st'
        'dif'
        'difs'
        'l'
        'll'
        'lgrep'
        'show'
        'fetch'
        'pull'
        'psh'
        # MyDevTools
        'cldir'
        'rmgh'
        'rmnode'
        # pnpm
        'pn'
        'pnvite'
        'pnnext'
        # PowerShell
        'e'
    )
}
