@{
    RootModule        = '.\New-MyAliasGit.psm1'
    ModuleVersion     = '0.0.1'
    GUID              = '2bdeccaa-b0c4-4e2d-8f5f-54cd754c7704'
    Author            = 'Admin'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Admin. All rights reserved.'
    FunctionsToExport = @(
        'Add-MyGit'
        'Add-MyGitP'
        'Add-MyGitI'
        'Move-MyGit'
        'Remove-MyGit'
        'Set-MyGitUnstage'
        'Set-MyGitCommit'
        'Set-MyGitCommitAll'
        'Set-MyGitCommitU'
        'Set-MyGitCommitAmend'
        'Set-MyGitCommitAmendNoEdit'
        'Reset-MyGitMixed'
        'Reset-MyGitSoft'
        'Reset-MyGitHard'
        'Restore-MyGit'
        'Set-MyGitCheckout'
        'Set-MyGitCheckoutB'
        'Set-MyGitBranch'
        'Set-MyGitBranchD'
        'Merge-MyGit'
        'Set-MyGitRebase'
        'Set-MyGitStash'
        'Set-MyGitStashU'
        'Pop-MyGit'
        'Set-MyGitDrop'
        'Set-MyGitClean'
        'Set-MyGitCleanX'
        'Get-MyGitStatus'
        'Get-MyGitDiff'
        'Get-MyGitDiffStaged'
        'Get-MyGitLog'
        'Show-MyGit'
        'Push-MyGit'
    )
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @(
        'a'
        'ap'
        'ai'
        'unst'
        'gmv'
        'grm'
        'c'
        'ca'
        'cu'
        'cam'
        'camn'
        'rem'
        'res'
        'reh'
        'restore'
        'che'
        'cheb'
        'bra'
        'brad'
        'merge'
        'rebase'
        'stash'
        'stashu'
        'pop'
        'drop'
        'cl'
        'clx'
        'st'
        'dif'
        'difs'
        'log'
        'show'
        'psh'
    )
    PrivateData       = @{
        PSData = @{
        }
    }
}
