@{
    RootModule        = '.\MyDevTools.psm1'
    ModuleVersion     = '0.0.1'
    FunctionsToExport = @(
        'Add-MyNpmScript'
        'Add-MyPackagesToNextJs'
        'Add-MyPackagesToVite'
        'Clear-MyCurrentDirectory'
        'Copy-MyFolderStructure'
        'Export-MyJSON'
        'Import-MyJSON'
        'Initialize-MyGit'
        'Initialize-MyNpm'
        'Install-MyEnvForNode'
        'Install-MyEnvForPython'
        'Install-MyESLint'
        'Install-MyGulp'
        'Install-MyNodemon'
        'Install-MyPrettier'
        'Install-MyReact'
        'Install-MyTailwindCss'
        'Install-MyTSNode'
        'Install-MyTypeDoc'
        'Install-MyTypeScript'
        'Install-MyVitest'
        'Install-MyVSCodeSettings'
        'Install-MyVSCodeSettingsForPwsh'
        'Install-MyVSCodeSettingsForPython'
        'Install-MyVSCodeSettingsForWeb'
        'Remove-MyAllFiles'
        'Remove-MyGitHistory'
        'Remove-MyNodeModulesDir'
        'Remove-MyNpmScript'
        'Rename-MyFileExtension'
        'Test-MyCommandExists'
        'Test-MyStrictPath'
    )
    AliasesToExport   = @(
        'cldir'
        'cptree'
        'ginit'
        'ninit'
        'rmfiles'
        'rmgh'
        'rmnodemodules'
        'renameextension'
    )
}
