@{
    RootModule        = 'MyDevTools.psm1'
    ModuleVersion     = '0.0.1'
    FunctionsToExport = @(
        'Add-NpmScript'
        'Add-VsCodeFrontendSetting'
        'Add-VsCodePowerShellSetting'
        'Copy-DirectoryStructure'
        'Export-Json'
        'Import-Json'
        'Initialize-GitRepository'
        'Initialize-NextJsProject'
        'Initialize-NodeDevelopment'
        'Initialize-NpmProject'
        'Initialize-ViteProject'
        'Initialize-VsCodeSetting'
        'Install-EsLint'
        'Install-Gulp'
        'Install-Nodemon'
        'Install-Prettier'
        'Install-React'
        'Install-TailwindCss'
        'Install-TsNode'
        'Install-TypeDoc'
        'Install-TypeScript'
        'Install-Vitest'
        'Remove-DirectoryFast'
        'Remove-NpmScript'
        'Rename-FileExtension'
        'Test-CommandExists'
        'Test-StrictPath'
    )
    AliasesToExport   = @(
        'cptree'
        'ginit'
        'ninit'
        'rmfiles'
        'rmdirf'
        'renext'
    )
}
