<#
.SYNOPSIS
Adds some required packages to a Vite.
You should install "pnpm" on the your system beforehand,
for example by using the command "corepack enable pnpm".
Otherwise this function wil throw an error.

.PARAMETER UseReact
Whether to support React.

.PARAMETER DeployToGitHubPages
Whether to use GitHub Pages to publish a site.
#>
function Add-MyPackagesToVite {
    [OutputType([void])]
    param (
        [switch]$UseReact,
        [switch]$DeployToGitHubPages
    )

    if (-not (Test-MyCommandExists -Command 'pnpm')) {
        throw 'A command "pnpm" could not be found. You can install pnpm by using the command "corepack enable pnpm".'
    }
    # You should select "TypeScript + SWC" in "Select a variant" when initializing Vite.
    if ($UseReact) {
        [hashtable]$package = Import-MyJSON -LiteralPath '.\package.json' -AsHashTable
        [bool]$hasViteJsPluginReactSwc = $package['devDependencies'].ContainsKey('@vitejs/plugin-react-swc')

        if (-not $hasViteJsPluginReactSwc) {
            throw '"@vitejs/plugin-react-swc" could not be found in package.json. You should select "TypeScript + SWC" in "Select a variant" when initializing Vite'
        }
    }

    Initialize-MyGit -UseNode
    git add .
    git commit -m 'Add all the files generated by Vite'

    # Install npm packages according to package.json generated by Vite
    pnpm i
    git add '.\package.json' '.\pnpm-lock.yaml'
    git commit -m 'Add pnpm as packageManager'

    # Add the alias `@/` -> `.\src` to the Vite config
    if ($UseReact) {
        Join-Path -Path $PSScriptRoot -ChildPath 'common\vite.config.ts' |
        Copy-Item -Destination '.\vite.config.ts'
        git add '.\package.json' '.\pnpm-lock.yaml' '.\vite.config.ts'
    }
    else {
        Join-Path -Path $PSScriptRoot -ChildPath 'common\vite.config.mjs' |
        Copy-Item -Destination '.\vite.config.mjs'
        git add '.\vite.config.mjs'
    }
    git commit -m 'Add the alias `@/` -> `./src/*` to the Vite config file'

    Install-MyTypeScript -IsVite -UseReact:$UseReact
    Install-MyESLint -IsViteReact:$UseReact
    Install-MyVitest
    Install-MyPrettier -UseTailwindcss
    Install-MyTailwindCss -IsVite
    Install-MyVSCodeSettingsForWeb

    # Add `--open` to `dev` and `preview` npm scirpts
    [hashtable]$package = Import-MyJSON -LiteralPath '.\package.json' -AsHashTable
    $package['scripts']['dev'] = 'vite --open'
    $package['scripts']['preview'] = 'vite preview --open'
    Export-MyJSON -LiteralPath '.\package.json' -CustomObject $package
    git add '.\package.json'
    git commit -m 'Add `--open` to `dev` and `preview` npm scirpt'

    <# vite.yml #>
    # Add vite.yml to deploy to GitHub Pages
    if ($DeployToGitHubPages) {
        if (Test-MyStrictPath -LiteralPath '.\.github\workflows\vite.yml' -PathType Leaf) {
            Write-Warning -Message '.\.github\workflows\vite.yml is already in place (skip).'
        }
        else {
            if (-not (Test-MyStrictPath -LiteralPath '.\.github' -PathType Container)) {
                New-Item -Path '.\' -Name '.github' -ItemType 'directory'
            }
            if (-not (Test-MyStrictPath -LiteralPath '.\.github\workflows' -PathType Container)) {
                New-Item -Path '.\.github' -Name 'workflows' -ItemType 'directory'
            }
            Join-Path -Path $PSScriptRoot -ChildPath 'common\vite.yml' |
            Copy-Item -Destination '.\.github\workflows\vite.yml'
            git add '.\.github\workflows\vite.yml'
            git commit -m 'Add vite.yml to deploy to GitHub Pages'
        }
    }

    Write-Host -Object '✅ Setup complete: Vite project is now ready! ' -ForegroundColor Green
}
