<#
.SYNOPSIS
Adds some required packages to a Vite.
You should install "pnpm" on your system beforehand,
for example by using the command "corepack enable pnpm".
Otherwise this function will throw an error.

.PARAMETER UseReact
Whether to support React.

.PARAMETER DeployToGitHubPages
Whether to use GitHub Pages to publish a site.
#>
function Add-MyPackagesToVite {
    [OutputType([void])]
    param (
        [switch]$UseReact,
        [switch]$DeployToGitHubPages
    )

    [hashtable]$splat = @{
        'Environment' = 'Vite'
    }
    if (-not (Test-MyCommandExists -Command 'pnpm')) {
        throw 'A command "pnpm" could not be found. You can install pnpm by using the command "corepack enable pnpm".'
    }
    # You should select "TypeScript + React Compiler (Rolldown)" in "Select a variant" when initializing Vite.
    if ($UseReact) {
        [hashtable]$package = Import-MyJSON -LiteralPath '.\package.json' -AsHashTable
        [bool]$hasBabelPluginReactCompiler = $package['devDependencies'] `
            -and $package['devDependencies'].ContainsKey('babel-plugin-react-compiler')

        $splat['Environment'] = 'ViteReact'
        if (-not $hasBabelPluginReactCompiler) {
            throw '"babel-plugin-react-compiler" could not be found in package.json.' +
            'You should select "TypeScript + React Compiler (Rolldown)" in "Select a variant" when initializing Vite.'
        }
    }

    Initialize-MyGit -UseNode
    git add .
    git commit -m 'Add all the files generated by Vite'

    # Install npm packages according to package.json generated by Vite
    pnpm i
    git add '.\package.json' '.\pnpm-lock.yaml'
    git commit -m 'Add pnpm as packageManager'

    # Add the alias `@/` -> `.\src` to the Vite config
    if ($UseReact) {
        Join-Path -Path $PSScriptRoot -ChildPath 'common\vite-react.config.ts' |
        Copy-Item -Destination '.\vite.config.ts' -Force
        Join-Path -Path $PSScriptRoot -ChildPath 'common\vite-react-index.css' |
        Copy-Item -Destination '.\src\index.css' -Force
        git add '.\package.json' '.\pnpm-lock.yaml' '.\vite.config.ts' '.\src\index.css'
    }
    else {
        Join-Path -Path $PSScriptRoot -ChildPath 'common\vite.config.mjs' |
        Copy-Item -Destination '.\vite.config.mjs' -Force
        Join-Path -Path $PSScriptRoot -ChildPath 'common\vite-style.css' |
        Copy-Item -Destination '.\src\style.css' -Force
        git add '.\vite.config.mjs' '.\src\style.css'
    }
    git commit -m 'Add the alias `@/` -> `./src/*` to the Vite config file'

    Install-MyTypeScript @splat
    Install-MyESLint @splat
    Install-MyVitest
    Install-MyPrettier -UseTailwindcss
    Install-MyTailwindCss -IsVite
    Install-MyVSCodeSettingsForWeb

    # Add `--open` to `dev` and `preview` npm scripts
    [hashtable]$package = Import-MyJSON -LiteralPath '.\package.json' -AsHashTable
    $package['scripts']['dev'] = 'vite --open'
    $package['scripts']['preview'] = 'vite preview --open'
    Export-MyJSON -LiteralPath '.\package.json' -CustomObject $package
    git add '.\package.json'
    git commit -m 'Add `--open` to `dev` and `preview` npm script'

    <# vite.yml #>
    # Add vite.yml to deploy to GitHub Pages
    if ($DeployToGitHubPages) {
        if (Test-Path -Path '.\.github\workflows\*.yml' -PathType Leaf) {
            Write-Warning -Message 'The workflow file is already in place (skip).'
        }
        else {
            $null = New-Item -Path '.\.github\workflows'-ItemType 'Directory' -Force
            Join-Path -Path $PSScriptRoot -ChildPath 'common\pnpm-vite.yml' |
            Copy-Item -Destination '.\.github\workflows\pnpm-vite.yml' -Force
            git add '.\.github\workflows\pnpm-vite.yml'
            git commit -m 'Add vite.yml to deploy to GitHub Pages'
        }
    }

    Write-Host -Object '✅ Setup complete: Vite project is now ready!' -ForegroundColor Green
}
